.TH lp-attach "1" "Oct 24 2012" "lptools"
.SH NAME
lp-attach \- attach a file to a Launchpad bug

.SH SYNOPSIS
.B lp-attach <\fIbugnumber\fR>

.SH DESCRIPTION
\fBlp-attach\fR attaches a file (read from stdin) as an attachment on a named
Launchpad bug.

.SH OPTIONS
Listed below are the command line options for \fBlp-attach\fR:
.TP
.BR <\fIbugnumber\fR>
Launchpad bug number to attach the file to.

.SH AUTHORS
\fBlp-attach\fR was written by Martin Pool <mbp@canonical.com>,
and this manual page was written by Nathan Handler <nhandler@ubuntu.com>.
