.TH lp-capture-bug-counts "1" "Oct 24 2012" "lptools"
.SH NAME
lp-capture-bug-counts \- view summary of number of bugs for a Launchpad project

.SH SYNOPSIS
.B lp-capture-bug-counts

.SH DESCRIPTION
\fBlp-capture-bug-counts\fR prints some statistics about a project. It can
quickly display the number of bugs with a particular status or with patches
attached that affect a project.

.SH AUTHORS
\fBlp-capture-bug-counts\fR was written by Martin Pool <mbp@canonical.com>,
and this manual page was written by Nathan Handler <nhandler@ubuntu.com>.
