.TH lp-force-branch-mirror "1" "Oct 24 2012" "lptools"
.SH NAME
lp-force-branch-mirror \- force a new import

.SH SYNOPSIS
.B lp-force-branch-mirror [\fIoptions\fR] \fIBRANCH\fR...

.SH DESCRIPTION
\fBlp-force-branch-mirror\fR forces the mirrorring of a code mirror.

.SH OPTIONS
Listed below are the command line options for \fBlp-force-branch-mirror\fR:
.TP
.BR PROJECT
The launchpad project to inspect (eg bzr)

.SH AUTHORS
\fBlp-force-branch-mirror\fR was written by Jelmer Vernooij <jelmber@samba.org>,
and this manual page was written by Nathan Handler <nhandler@ubuntu.com>.
