.TH lp-milestone2ical "1" "Oct 24 2012" "lptools"
.SH NAME
lp-milestone2ical \- convert project milestones to iCalendar

.SH SYNOPSIS
.B lp-milestone2ical <\fIproject\fR>

.SH DESCRIPTION
\fBlp-milestone2ical\fR will convert all the milestones on a project or project
group, into an iCalendar 2.0 format file, for importing into a calendar program.

.SH OPTIONS
Listed below are the command line options for \fBlp-milestone2ical\fR:
.TP
.BR project
The launchpad project whose milestones you wish to convert

.SH AUTHORS
\fBlp-milestone2ical\fR was written by Rodney Dawes <rodney.dawes@canonical.com>,
and this manual page was written by Nathan Handler <nhandler@ubuntu.com>.
