.TH lp-recipe-status "1" "Oct 24 2012" "lptools"
.SH NAME
lp-recipe-status \- show the status of the recipes owned by a particular user

.SH SYNOPSIS
.B lp-recipe-status [\fIoptions\fR] <\fIperson\fR>

.SH DESCRIPTION
\fBlp-recipe-status\fR will render a status table for all of the recipe builds
owned by the specified person.

.SH OPTIONS
Listed below are the command line options for \fBlp-recipe-status\fR:
.TP
.BR <\fIperson\fR>
The Launchpad person or team whose recipes to check
.TP
.B \-\-html
Generate HTML

.SH AUTHORS
\fBlp-recipe-status\fR was written by Jelmer Vernooij <jelmer@samba.org>,
and this manual page was written by Nathan Handler <nhandler@ubuntu.com>.
