.TH lp-review-notifier "1" "Oct 24 2012" "lptools"
.SH NAME
lp-review-notifier \- desktop notifier about reviews that can be done

.SH SYNOPSIS
.B lp-review-notifier <\fIproject1\fR> [[\fIproject2\fR] ...]

.SH DESCRIPTION
\fBlp-review-notifier\fR will present notifications for changes to merge
proposals on a project. You currently must pass the list of projects on the
command line.

.SH OPTIONS
Listed below are the command line options for \fBlp-review-notifier\fR:
.TP
.BR <\fIproject1\fR> [[\fIproject2\fR] ...]
List of projects to display notifications for changes to merge proposals for.

.SH AUTHORS
\fBlp-review-notifier\fR was written by Rodney Dawes <rodney.dawes@canonical.com>,
and this manual page was written by Nathan Handler <nhandler@ubuntu.com>.
