.TH lp-remove-team-members "1" "Oct 24 2012" "lptools"
.SH NAME
lp-remove-team-members \- remove members from a Launchpad team

.SH SYNOPSIS
.B lp-remove-team-members <\fIteam\fR> <\fIMEMBER\fR>...

.SH DESCRIPTION
\fBlp-remove-team-members\fR allows you to quickly bulk remove users from a team.

.SH OPTIONS
Listed below are the command line options for \fBlp-remove-team-members\fR:
.TP
.BR <\fIteam\fR>
Launchpad team to remove members from
.TP
.B <\fIMEMBER\fR>...
List of members to remove from the team

.SH AUTHORS
\fBlp-remove-team-members\fR was written by Martin Pool <mbp@canonical.com>,
and this manual page was written by Nathan Handler <nhandler@ubuntu.com>.
